"""Initiate tables

Revision ID: 1
Revises: 
Create Date: 2020-12-31 23:13:03.669543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'markers',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('name', sa.String()),
        sa.Column('entry_at', sa.DateTime(), server_default=sa.func.current_timestamp())
    )
    op.create_index('ix_marker_name', 'markers', ['name'], unique=True)
    op.create_table(
        'samples',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('name', sa.String()),
        sa.Column('entry_at', sa.DateTime(), server_default=sa.func.current_timestamp())
    )
    op.create_index('ix_sample_name', 'samples', ['name'], unique=True)
    op.create_table(
        'cells',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('sample_id', sa.Integer()),
        sa.Column('sample_cell_id', sa.Integer(), nullable=True),
        sa.Column('entry_at', sa.DateTime(), server_default=sa.func.current_timestamp()),
        sa.Column('area', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('eccentricity', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('extent', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('majoraxislength', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('minoraxislength', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('orientation', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('solidity', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('x_centroid', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('y_centroid', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('column_centroid', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('row_centroid', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('alpha_sma__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('alpha_sma__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('ar__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('ar__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('cd11b__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('cd11b__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('cd14__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('cd14__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('cd163__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('cd163__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('cd20__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('cd20__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('cd3__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('cd3__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('cd45__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('cd45__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('cd45_1__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('cd45_1__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('cd45_2__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('cd45_2__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('cd45r_1__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('cd45r_1__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('cd45r_2__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('cd45r_2__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('cd45ro__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('cd45ro__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('cd4_1__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('cd4_1__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('cd4_2__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('cd4_2__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('cd68__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('cd68__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('cd8a__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('cd8a__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('ck__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('ck__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('ck_14_1__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('ck_14_1__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('ck_14_2__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('ck_14_2__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('ck_17__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('ck_17__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('ck_19__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('ck_19__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('ck_7__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('ck_7__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('cyclind1__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('cyclind1__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('dapi_1__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('dapi_1__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('dapi_2__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('dapi_2__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('dapi_3__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('dapi_3__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('dapi_4__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('dapi_4__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('dapi_5__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('dapi_5__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('dapi_6__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('dapi_6__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('dapi_7__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('dapi_7__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('dapi_8__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('dapi_8__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('e_cadherin__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('e_cadherin__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('egfr__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('egfr__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('er_alpha__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('er_alpha__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('erk_1__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('erk_1__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('foxp3__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('foxp3__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('goat_igg_af488__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('goat_igg_af488__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('goat_igg_af555__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('goat_igg_af555__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('goat_igg_af647__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('goat_igg_af647__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('granzymeb__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('granzymeb__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('h2a_x__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('h2a_x__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('her2__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('her2__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('hes_1__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('hes_1__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('histone__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('histone__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('hla_a__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('hla_a__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('ki_67__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('ki_67__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('lag_3__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('lag_3__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('p21__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('p21__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('parp__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('parp__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('pd_1__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('pd_1__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('pd_l1__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('pd_l1__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('pr__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('pr__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('rad51__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('rad51__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('rb__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('rb__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('vimentin__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column('vimentin__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True),
        sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ondelete='CASCADE'),
    )
    op.create_table(
        'sample_marker_association',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('sample_id', sa.Integer()),
        sa.Column('marker_id', sa.Integer()),
        sa.Column('channel_number', sa.Integer(), nullable=True),
        sa.Column('cycle_number', sa.Integer(), nullable=True),
        sa.Column('entry_at', sa.DateTime(), server_default=sa.func.current_timestamp()),
        sa.ForeignKeyConstraint(['marker_id'], ['markers.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ondelete='CASCADE'),
    )
    op.create_index('ix_sample_marker_associate', 'sample_marker_association', ['sample_id', 'marker_id', 'channel_number'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sample_marker_associate', table_name='sample_marker_association')
    op.drop_table('sample_marker_association')
    op.drop_table('cells')
    op.drop_index('ix_sample_name', table_name='samples')
    op.drop_table('samples')
    op.drop_index('ix_marker_name', table_name='markers')
    op.drop_table('markers')
    # ### end Alembic commands ###
