"""Add filter, wavelength columns in sample_marker_association table

Revision ID: 2
Revises: 1
Create Date: 2021-02-13 22:54:15.423290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2'
down_revision = '1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample_marker_association',
                  sa.Column('emission_wavelength', sa.Integer(), nullable=True))
    op.add_column('sample_marker_association',
                  sa.Column('excitation_wavelength', sa.Integer(), nullable=True))
    op.add_column('sample_marker_association',
                  sa.Column('filter', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sample_marker_association', 'filter')
    op.drop_column('sample_marker_association', 'excitation_wavelength')
    op.drop_column('sample_marker_association', 'emission_wavelength')
    # ### end Alembic commands ###
