"""Manual mapping of column names

Revision ID: 2
Revises: 1
Create Date: 2021-01-08 16:56:08.787984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2'
down_revision = '1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cells', sa.Column('cd4__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True))
    op.add_column('cells', sa.Column('cd4__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True))
    op.add_column('cells', sa.Column('ck14__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True))
    op.add_column('cells', sa.Column('ck14__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True))
    op.add_column('cells', sa.Column('dapi__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True))
    op.add_column('cells', sa.Column('dapi__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True))
    op.add_column('cells', sa.Column('er__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True))
    op.add_column('cells', sa.Column('er__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True))

    op.alter_column('cells', 'ck_14_1__cell_masks', new_column_name='ck14_1__cell_masks')
    op.alter_column('cells', 'ck_14_1__nuclei_masks', new_column_name='ck14_1__nuclei_masks')
    op.alter_column('cells', 'ck_14_2__cell_masks', new_column_name='ck14_2__cell_masks')
    op.alter_column('cells', 'ck_14_2__nuclei_masks', new_column_name='ck14_2__nuclei_masks')
    op.alter_column('cells', 'ck_17__cell_masks', new_column_name='ck17__cell_masks')
    op.alter_column('cells', 'ck_17__nuclei_masks', new_column_name='ck17__nuclei_masks')
    op.alter_column('cells', 'ck_7__nuclei_masks', new_column_name='ck7__nuclei_masks')
    op.alter_column('cells', 'ck_7__cell_masks', new_column_name='ck7__cell_masks')
    op.alter_column('cells', 'ck_19__cell_masks', new_column_name='ck19__cell_masks')
    op.alter_column('cells', 'ck_19__nuclei_masks', new_column_name='ck19__nuclei_masks')
    op.alter_column('cells', 'cyclind1__cell_masks', new_column_name='cyclin_d1__cell_masks')
    op.alter_column('cells', 'cyclind1__nuclei_masks', new_column_name='cyclin_d1__nuclei_masks') 
    op.alter_column('cells', 'ki_67__cell_masks', new_column_name='ki67__cell_masks')
    op.alter_column('cells', 'ki_67__nuclei_masks', new_column_name='ki67__nuclei_masks')
    op.alter_column('cells', 'pd_1__cell_masks', new_column_name='pd1__cell_masks')
    op.alter_column('cells', 'pd_1__nuclei_masks', new_column_name='pd1__nuclei_masks')
    op.alter_column('cells', 'majoraxislength', new_column_name='major_axis_length')
    op.alter_column('cells', 'minoraxislength', new_column_name='minor_axis_length')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cells', 'ck14_1__cell_masks', new_column_name='ck_14_1__cell_masks')
    op.alter_column('cells', 'ck14_1__nuclei_masks', new_column_name='ck_14_1__nuclei_masks')
    op.alter_column('cells', 'ck14_2__cell_masks', new_column_name='ck_14_2__cell_masks')
    op.alter_column('cells', 'ck14_2__nuclei_masks', new_column_name='ck_14_2__nuclei_masks')
    op.alter_column('cells', 'ck17__cell_masks', new_column_name='ck_17__cell_masks')
    op.alter_column('cells', 'ck17__nuclei_masks', new_column_name='ck_17__nuclei_masks')
    op.alter_column('cells', 'ck7__nuclei_masks', new_column_name='ck_7__nuclei_masks')
    op.alter_column('cells', 'ck7__cell_masks', new_column_name='ck_7__cell_masks')
    op.alter_column('cells', 'ck19__cell_masks', new_column_name='ck_19__cell_masks')
    op.alter_column('cells', 'ck19__nuclei_masks', new_column_name='ck_19__nuclei_masks')
    op.alter_column('cells', 'cyclin_d1__cell_masks', new_column_name='cyclind1__cell_masks')
    op.alter_column('cells', 'cyclin_d1__nuclei_masks', new_column_name='cyclind1__nuclei_masks')
    op.alter_column('cells', 'ki67__cell_masks', new_column_name='ki_67__cell_masks')
    op.alter_column('cells', 'ki67__nuclei_masks', new_column_name='ki_67__nuclei_masks')
    op.alter_column('cells', 'pd1__cell_masks', new_column_name='pd_1__cell_masks')
    op.alter_column('cells', 'pd1__nuclei_masks', new_column_name='pd_1__nuclei_masks')
    op.alter_column('cells', 'major_axis_length', new_column_name='majoraxislength')
    op.alter_column('cells', 'minor_axis_length', new_column_name='minoraxislength')

    op.drop_column('cells', 'er__nuclei_masks')
    op.drop_column('cells', 'er__cell_masks')
    op.drop_column('cells', 'dapi__nuclei_masks')
    op.drop_column('cells', 'dapi__cell_masks')
    op.drop_column('cells', 'ck14__nuclei_masks')
    op.drop_column('cells', 'ck14__cell_masks')
    op.drop_column('cells', 'cd4__nuclei_masks')
    op.drop_column('cells', 'cd4__cell_masks')
    # ### end Alembic commands ###
