"""Update two markers

Revision ID: 3
Revises: 2
Create Date: 2021-01-28 14:27:37.051296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3'
down_revision = '2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cells', sa.Column('muc1__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True))
    op.add_column('cells', sa.Column('muc1__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True))
    op.drop_column('cells', 'phh3__nuclei_masks')
    op.drop_column('cells', 'phh3__cell_masks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cells', sa.Column('phh3__cell_masks', sa.NUMERIC(precision=15, scale=4), autoincrement=False, nullable=True))
    op.add_column('cells', sa.Column('phh3__nuclei_masks', sa.NUMERIC(precision=15, scale=4), autoincrement=False, nullable=True))
    op.drop_column('cells', 'muc1__nuclei_masks')
    op.drop_column('cells', 'muc1__cell_masks')
    # ### end Alembic commands ###
