"""Add columns CAV1, pS6RP, DAPI_11, etc.

Revision ID: 4
Revises: 3
Create Date: 2021-01-12 18:15:37.224780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4'
down_revision = '3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cells', sa.Column('cav1__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True))
    op.add_column('cells', sa.Column('cav1__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True))
    op.add_column('cells', sa.Column('dapi_10__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True))
    op.add_column('cells', sa.Column('dapi_10__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True))
    op.add_column('cells', sa.Column('dapi_11__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True))
    op.add_column('cells', sa.Column('dapi_11__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True))
    op.add_column('cells', sa.Column('dapi_9__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True))
    op.add_column('cells', sa.Column('dapi_9__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True))
    op.add_column('cells', sa.Column('ps6rp__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True))
    op.add_column('cells', sa.Column('ps6rp__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cells', 'ps6rp__nuclei_masks')
    op.drop_column('cells', 'ps6rp__cell_masks')
    op.drop_column('cells', 'dapi_9__nuclei_masks')
    op.drop_column('cells', 'dapi_9__cell_masks')
    op.drop_column('cells', 'dapi_11__nuclei_masks')
    op.drop_column('cells', 'dapi_11__cell_masks')
    op.drop_column('cells', 'dapi_10__nuclei_masks')
    op.drop_column('cells', 'dapi_10__cell_masks')
    op.drop_column('cells', 'cav1__nuclei_masks')
    op.drop_column('cells', 'cav1__cell_masks')
    # ### end Alembic commands ###
