"""Add and change columns for Donky_IgG-AF555, LAG3 etc.

Revision ID: 5
Revises: 4
Create Date: 2021-01-13 11:06:53.345609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5'
down_revision = '4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cells', sa.Column('donkey_igg_af555__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True))
    op.add_column('cells', sa.Column('donkey_igg_af555__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True))
    op.add_column('cells', sa.Column('donkey_igg_af647__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True))
    op.add_column('cells', sa.Column('donkey_igg_af647__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True))
    op.add_column('cells', sa.Column('erk1_1__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True))
    op.add_column('cells', sa.Column('erk1_1__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True))
    op.add_column('cells', sa.Column('erk1_2__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True))
    op.add_column('cells', sa.Column('erk1_2__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True))
    op.add_column('cells', sa.Column('lag3_1__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True))
    op.add_column('cells', sa.Column('lag3_1__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True))
    op.add_column('cells', sa.Column('lag3_2__cell_masks', sa.Numeric(precision=15, scale=4), nullable=True))
    op.add_column('cells', sa.Column('lag3_2__nuclei_masks', sa.Numeric(precision=15, scale=4), nullable=True))

    op.alter_column('cells', 'erk_1__cell_masks', new_column_name='erk1__cell_masks')
    op.alter_column('cells', 'erk_1__nuclei_masks', new_column_name='erk1__nuclei_masks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cells', 'erk1__nuclei_masks', new_column_name='erk_1__nuclei_masks')
    op.alter_column('cells', 'erk1__cell_masks', new_column_name='erk_1__cell_masks')
    
    op.drop_column('cells', 'lag3_2__nuclei_masks')
    op.drop_column('cells', 'lag3_2__cell_masks')
    op.drop_column('cells', 'lag3_1__nuclei_masks')
    op.drop_column('cells', 'lag3_1__cell_masks')
    op.drop_column('cells', 'erk1_2__nuclei_masks')
    op.drop_column('cells', 'erk1_2__cell_masks')
    op.drop_column('cells', 'erk1_1__nuclei_masks')
    op.drop_column('cells', 'erk1_1__cell_masks')
    op.drop_column('cells', 'donkey_igg_af647__nuclei_masks')
    op.drop_column('cells', 'donkey_igg_af647__cell_masks')
    op.drop_column('cells', 'donkey_igg_af555__nuclei_masks')
    op.drop_column('cells', 'donkey_igg_af555__cell_masks')
    # ### end Alembic commands ###
